version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: github-api
    restart: always
    ports:
      - '3000:3000'
    environment:
      - PORT=${PORT}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_USERNAME=${GITHUB_USERNAME}
      - THROTTLE_TTL=${THROTTLE_TTL}
      - THROTTLE_LIMIT=${THROTTLE_LIMIT}
